README.md
helm/helm-release.bzl
helm/helm-release.sh.tpl
helm/helm.bzl

`helm_release` is used to create and deploy a new release in a Kubernetes Cluster.
Only `Helm 2` is supported for the moment.
It has support for secrets via helm secrets (sops), which allows to have encrypted values files in the Git repository.
This rule is an executable. It needs `run` instead of `build` to be invoked.
It relies in existing local kubernetes config (`~/.kube/config`).
Example:
```
helm_release(
name = "chart_install",
chart = ":chart",
namespace = "myapp",
tiller_namespace = "tiller-system",
release_name = "release-name",
values_yaml = glob(["charts/myapp/values.yaml"]),
secrets_yaml = glob(["charts/myapp/secrets.*.yaml"]),
sops_yaml = ".sops.yaml",
)
```

(helm) Added helm_release rule

---

helm/helm-chart-package.bzl
helm/helm-chart-package.sh.tpl
tests/charts/nginx-with-deps/BUILD
tests/charts/nginx/BUILD
tests/rules/package_spec_test.go

Do not fail if no `image`, `image_repository` and `image_tag` are provided to `helm_chart` rule.
Logic refactor of `helm_chart` rule.

Remove dependency of image_repository and image_tag

---

README.md
WORKSPACE
repositories/docker_deps.bzl
repositories/repositories.bzl
tests/charts/nginx-with-deps/BUILD

Implement a function to automatically load all `rules_docker` dependencies.
This is useful until recursive workspaces get implemented.
This PR has the changes of PR https://github.com/masmovil/bazel-rules/pull/5 .
So https://github.com/masmovil/bazel-rules/pull/5 has to be merged before!

Include rules_docker dependencies

---

README.md
helm/helm-release.bzl
helm/helm-release.sh.tpl
repositories/repositories.bzl
repositories/sops_repositories.bzl
sops/BUILD
sops/sops-decrypt.bzl
sops/sops-decrypt.sh.tpl
sops/sops.bzl
sops/sops_decrypt.bzl
toolchains/sops/BUILD
toolchains/sops/sops_toolchain.bzl

Added `sops_decrypt` rule using defined `sops` toolchain.
You can decrypt multiple secrets using this rule, and pass them to other rules (e.g `helm_release`).
It uses gcp_kms by default, but any provider could be used in the near future.

fature: support secrets decrypt using sops

---

README.md
gcs/BUILD
gcs/gcs-upload.bzl
gcs/gcs-upload.sh.tpl
gcs/gcs.bzl

`gcs_upload` is used to upload a single file to a Google Cloud Storage bucket.
Example of use:
```python
gcs_upload(
name = "push",
src = ":file",
destination = "gs://my-bucket/file.zip"
)
```
The following attributes are accepted by the rule (some of them are mandatory).
|  Attribute | Mandatory| Default | Notes |
| ---------- | --- | ------ | -------------- |
| src | yes | - | Source file label |
| destination | yes | - | Destination path in GCS (in form of`gs://mybucket/file`) It supports the use of `stamp_variables`. |

Added Google Cloud Storage upload rule

---

helm/helm-push.bzl

If chart-museum chart repository is not configured with `server.AllowForceOverwrite` then
it will not update the remote object and it will return a `409` http.StatusConflict code.
We will ignore it.

Do not fail if chart repository does not allow force overwrite

---

helm/helm-chart-package.sh.tpl

Deleted source yaml files will still get included because of obsolete cached files in the temp working dir. Removing this ensure newly built templates only contains up-to-date files.

Remove temp working dir after packaging

---

README.md
helm/helm-chart-package.bzl

Hello folks 👋🏻   
First off, love the work you've being doing here 💯 
In our usecase, we have a list of common Helm templates that are shared across all of our charts. I didn't see this option in `helm_chart` so I thought I'd add it.
This PR introduces an additional attribute, called `additional_templates`, to specify such targets. The targets will be copied under the `templates/` folder before packing the chart in a tarball.

feat: add additional templates to helm_chart

---

helm/helm-chart-package.bzl

Include extracted dependencies dir in outputs.
Fixes a bug where listed dependencies give the error "Chart.yaml not found", since the output of the `tar -xzf` command is not listed in Bazel's outputs.
Without this fix, dependencies can't be listed in the `dependencies:` section of the `Chart.yaml`.

Fix a bug where extracted dependencies dir aren't in Bazel output

---

repositories/repositories.bzl
repositories/sops_repositories.bzl
toolchains/sops/BUILD

Update sops to 3.7.3
* Splits arm64/amd64 versions for linux/darwin
* Permits helm_release() with SOPS secrets on M2 Mac

Update sops to 3.7.3, permitting sops_() actions on M2 Mac

---

toolchains/gpg/BUILD
toolchains/helm-3/BUILD
toolchains/helm/BUILD
toolchains/kubectl/BUILD
toolchains/sops/BUILD
toolchains/yq/BUILD

Context: https://github.com/bazelbuild/bazel/issues/8622
Using `@bazel_tools//platforms` is no longer allowed in Bazel v6. This PR replaces all references and uses `@platforms//os` instead.

Replace `@bazel_tools//platforms` with `@platforms//os`

---

WORKSPACE
toolchains/sops/BUILD

In order to support bazel 6 rules docker needs to be upgraded to use new platform constraints.

feat: upgrade docker rules

---

toolchains/helm-3/BUILD

This allows the helm binary in the toolchain to be used by other rules.
An example is running Terratest helm tests. This shells out the the helm binary, if this is not on the PATH it fails. 
Making the toolchain_type public enables the following to reference the helm binary.
```
helm_toolchain = ctx.toolchains["@com_github_masmovil_bazel_rules//toolchains/helm-3:toolchain_type"].helminfo
helm = helm_toolchain.tool.files.to_list()[0]
```

Make helm-3 toolchain_type public

---

MODULE.bazel
helm/private/helm_lint_test.bzl

Use `short_path` instead of `path` in `helm_lint_test.bzl` tested on **mm-monorepo** over bazel 7.4
With `path`
```
(09:01:54) FAIL: //pkg/commons/helm/bitnami-common:chart_lint (see /private/var/tmp/_bazel_carlos.gamez/35fae358f928ae0e57c2ebd504b42380/execroot/_main/bazel-out/darwin_arm64-fastbuild/testlogs/pkg/commons/helm/bitnami-common/chart_lint/test.log)
(09:01:54) INFO: From Testing //pkg/commons/helm/bitnami-common:chart_lint:
==================== Test output for //pkg/commons/helm/bitnami-common:chart_lint:
/private/var/tmp/_bazel_carlos.gamez/35fae358f928ae0e57c2ebd504b42380/sandbox/darwin-sandbox/3/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/pkg/commons/helm/bitnami-common/chart_lint.runfiles/_main/pkg/commons/helm/bitnami-common/chart_lint: line 2: …
```

fix(rules|lint): Use short_path

---

helm/private/helm_push.bzl

Use **.short_path** instead of **.path** to fix Bazel 7 compatibility.
tested on [mm-monorepo ](https://ci-masstack.masstack.com/job/mas-stack/job/mm-monorepo-publish-pr/job/PR-58716/10/pipeline-graph/)over Bazel 7.4.1 versión

fix(helm_push): Fix use helm_bin.short_path

---

docs/helm_release.md
docs/helm_uninstall.md
docs/k8s_namespace.md
helm/private/helm_release.bzl
helm/private/helm_uninstall.bzl

This pull request includes several changes to the documentation and implementation of the `helm_release` and `helm_uninstall` rules. The main focus is on correcting and clarifying the usage of the `kubernetes_context` attribute.
Documentation updates:
* [`docs/helm_release.md`](diffhunk://#diff-a4cc2c326309a4b4fe8bb6ca85ce7b45801134eedb29013b5fe65c405fb867c2L49-R49): Corrected the `kubernetes_context` attribute description and fixed a typo in the example usage. [[1]](diffhunk://#diff-a4cc2c326309a4b4fe8bb6ca85ce7b45801134eedb29013b5fe65c405fb867c2L49-R49) [[2]](diffhunk://#diff-a4cc2c326309a4b4fe8bb6ca85ce7b45801134eedb29013b5fe65c405fb867c2L95-R95)
* [`docs/helm_uninstall.md`](diffhunk://#diff-c359b7aa268b55e8006b08796d142616540154e7df8af4a21c011f4368d03e22L28-R28): Updated the …

fix(helm): use bin short_path and kubernetes_context as string

---

MODULE.bazel

Fixes #95 
In a build on macOS/arm64 or macOS/x86_64, the `zlib-1.2.13/zutil.h` header file has non-mututally-exclusive `#define` statements that fail the build:
```
#if defined(MACOS) || defined(TARGET_OS_MAC)
#endif
...
#ifdef __APPLE__
#endif
```
This is a transitive dependency through `@bazel_tools` (zlib-1.2.13) and `@protobuf` (zlib-1.2.11).  by providing a `bazel_dep` with a direct dependency, we override the transitive.  We therefore avoid the error and update our dependency ahead of moving to newer `bazel` versions.

fix: override newer zlib to unblock build on macos

---

.bazelrc

Without this change, `bazel query //...` fails because the `--enable_bzlmod` isn't activated, so the dependencies in `MODULE.bazel` are not available:
```
$ bazel query //... 
Starting local Bazel server and connecting to it...
ERROR: error loading package under directory '': error loading package 'docs': Unable to find package for @aspect_bazel_lib//lib:write_source_files.bzl: The repository '@aspect_bazel_lib' could not be resolved: Repository '@aspect_bazel_lib' is not defined.
```
With this change, `build` (and `test`) should still function, but additionally, `bazel query` works as well: `bzlmod` is activated, so `MODULE.bazel` is parsed, and the dependencies are available.
```
$ bazel query //... 
//docs:gcs_docs
//docs:gcs_docs_stardoc
//docs:helm_chart_docs …
```

fix: Update .bazelrc to allow functional non-build (ie query)

---

.github/workflows/ci-tests.yaml

This PR adds to the PR CI so that after the basic test runs, the examples are also run.
- as commented in CI, a single directory is not suitable for rules_bazel_integration_tests
- even so, since rules_bazel_integration_tests is sequential, I'd prefer to run them through a marix so that examples build In parallel but dependent on the basic test's successful completion
- `.bazelignore` keeps the `examples` entry: the `cd examples` in CI causes the `//.bazelignore` to be ineffective
This would have caught the issue in #98 as well.

ci: exercise examples to validate on CI

---

examples/chart_multi_version/BUILD.bazel
examples/chart_multi_version/test_chart/Chart.yaml
examples/chart_multi_version/test_chart/templates/_helpers.tpl
examples/chart_multi_version/test_chart/templates/deployment.yaml
examples/chart_multi_version/test_chart/templates/svc.yaml
examples/chart_multi_version/test_chart/values.yaml
helm/defs.bzl
helm/helm.bzl
helm/private/chart_srcs.bzl
helm/private/helm_chart.bzl

When you have multiple `helm_chart` rules in the same BUILD file with the same chart name (but with different versions), builds fail because all target outputs have the same name.
This PR try to solve this by appending the version of the chart to the name of the `helm_chart` output, as helm cli does. 
Only the chart version will be appended to the name if it's provided by argument to the `helm_chart` rule.

fix(helm-chart): append chart version to the packaged output chart name
